stages:
  - build
  - test
  - docker

maven-build:
  stage: build
  script: 
    - export PATH=/opt/apache-maven-3.8.2/bin:$PATH
    - mvn install -DskipTests
  artifacts:
    paths:
      - target/*.jar

test :
  stage : test
  script :
    - echo "test"

docker-build:
  stage: docker
  script:
    - docker build -t worldauditachat .
  only :
    - master
docker-run:
  stage: docker
  script:
    - docker run -d -p 8095:8095 --name worldaudit --link bd-xcompta worldauditachat
  
  only :
    - master
